include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/GraphViz.cmake)
set(GRAPHVIZ_ENABLE_UNKNOWN_LIBS OFF)
set(GRAPHVIZ_ENABLE_CUSTOM_TARGETS ON)

graphviz(OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/graphviz IGNORE_TARGETS SDK CONAN)
